### ISSUE TITLE
Сверстать input

### ISSUE THREAD

**Issue by alex-koshara** [alex-koshara/pink#1]
![input](https://cloud.githubusercontent.com/assets/16765673/20576113/88171354-b1cd-11e6-8017-5a6fd282a2ac.png)

Передаваемые поля:
- label
- ~~input type~~
- input name
- input value
- placeholder
- required
- disabled

Модификация где label находится под input
![input--mod](https://cloud.githubusercontent.com/assets/16765673/20576345/a910e606-b1ce-11e6-92c4-3a78ac6c2947.png)

**Comment by isqua** [comment]
Ещё инпуты бывают задизабленные.
