### ISSUE TITLE
Сверстать радио-инпуты

### ISSUE THREAD

**Issue by isqua** [alex-koshara/pink#12]
![image](https://cloud.githubusercontent.com/assets/16765673/20576461/1a16f6d8-b1cf-11e6-962d-367c0dd5d6e5.png)

Сетку пока не делай, пусть просто будут на странице формы где-нибудь и торчат сразу в центровщике. Если ты сначала сделаешь текстовые инпуты, то сложи радио между инпутами «фио» и «номер телефона». А если нет, то просто на странице формы.

**Comment by alex-koshara** [comment]
а ничего, что я их тырю с нашего прошлого проекта?

**Comment by isqua** [comment]
Мы потому и не удалили его, а переименовали, чтобы тырить. Только тырь внимательно: сам проверяй что тыришь и правь, если надо.
