### ISSUE TITLE
Сверстать radio

### ISSUE THREAD

**Issue by alex-koshara** [alex-koshara/pink#2]
![image](https://cloud.githubusercontent.com/assets/16765673/20576461/1a16f6d8-b1cf-11e6-962d-367c0dd5d6e5.png)

Передаваемые поля:
- label
- input name
- input value
- disabled

Обратить внимание на radio, является не прозрачной.
Выравнивание radio по baseline первой строки label

**Comment by isqua** [comment]
Ещё может быть disabled.
