### ISSUE TITLE
Сверстать checkbox

### ISSUE THREAD

**Issue by alex-koshara** [alex-koshara/pink#3]
![image](https://cloud.githubusercontent.com/assets/16765673/20576737/3489b810-b1d0-11e6-8b97-5944bd09ccdb.png)

Передаваемые поля:
- label
- input name
- input value
- disabled

Обратить внимание на checkbox, является не прозрачным.
Выравнивание checkbox по baseline первой строки label

**Comment by isqua** [comment]
Может быть задизабленным. А ещё один из пунктов может быть по умолчанию отмечен.
