### ISSUE TITLE
Сверстать textarea

### ISSUE THREAD

**Issue by alex-koshara** [alex-koshara/pink#4]
![image](https://cloud.githubusercontent.com/assets/16765673/20576840/a2ef8c12-b1d0-11e6-9cc6-09c694a1c72e.png)

передаваемые атрибуты:
- placeholder
- name
- required

**Comment by isqua** [comment]
Не хватает инфы про API.

**Comment by isqua** [comment]
Ещё у текстарий в уголке есть ресайзилка:
<img width="218" alt="a_pen_by_isqua" src="https://cloud.githubusercontent.com/assets/529247/20651665/5ed8afe0-b4fa-11e6-845b-cf1b388bac17.png">

Надо разрешить ресайз только по вертикали. Если тянуть по горизонтали, то страница разъедется.

И ещё предлагаю фичу: менять высоту текстарии автоматически по мере ввода текста.Чтобы в ней не появлялось скроллинга: [видосик](https://www.dropbox.com/s/dfpdckmmula06or/textarea-autoresize_gmat4.mp4?dl=0). Для этого понадобиться написать немного JS. Совсем чуть-чуть. Скорее всего тебе понадобится свойство [scrollHeight](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollHeight).
