### ISSUE TITLE
Сверстать btn

### ISSUE THREAD

**Issue by alex-koshara** [alex-koshara/pink#5]
![image](https://cloud.githubusercontent.com/assets/16765673/20577009/6c7dde4e-b1d1-11e6-8ca0-9f477a2f52ee.png)

**Блок**: `btn`
`+btn({
  tag: "a" || "button",
  class: "btn--round",
  value: "кнопка",
  disabled: true || false,
  type: "button"
})`

Стили:
- квадратная
- с заливкой

**Модификатор кнопки!**
**Модификатор**: `btn--round`
Учесть, что кнопки могут быть с border-radius:
![image](https://cloud.githubusercontent.com/assets/16765673/20577026/842d3fb2-b1d1-11e6-994b-49f7f6b1dd3c.png)
Стили:
- закругления border
- фон может быть прозрачный
- отличается font-size
- отличается line-height

Кнопки могут быть задизейблены

**Comment by isqua** [comment]
Какое АПИ?

**Comment by alex-koshara** [comment]
up

**Comment by isqua** [comment]
А вот кнопка скачать приложение что делает?

**Comment by alex-koshara** [comment]
нажимается 🎉

**Comment by isqua** [comment]
Да, про то, что она ссылка. А кнопки в форме — кнопки. И ещё у разных кнопок бывает разный атрибут type.

**Comment by alex-koshara** [comment]
up

**Comment by isqua** [comment]
М.б. объединить type с tag? Типа type: button|submit|link?

**Comment by alex-koshara** [comment]
это получается через условия в шаблонизаторе? Да, норм идея :)
