### ISSUE TITLE
Сверстать кнопку открытия\закрытия меню

### ISSUE THREAD

**Issue by alex-koshara** [alex-koshara/pink#7]
![image](https://cloud.githubusercontent.com/assets/16765673/20608542/e71ca578-b293-11e6-8289-5c79bd427279.png)

Блок: `button.hamburger`

API: `+hamburger({ mod: "hamburger--open" })`

Состояния кнопки:
- крестик - меню открыто (модификатор `hamburger--open`)
- три полоски - меню закрыто

Видно на мобильной версии и планшетной

**Comment by alex-koshara** [comment]
up

**Comment by isqua** [comment]
А точно кнопку надо отдельно верстать? Кмк, она сама по себе не имеет смысла и можно делать её прям в меню #8 Дискасс?

**Comment by isqua** [comment]
> А точно кнопку надо отдельно верстать? Кмк, она сама по себе не имеет смысла и можно делать её прям в меню 

Как ты думаешь?

**Comment by alex-koshara** [comment]
согласен, но пока не будет в мастере Хедер, бесполезно, как я понял :)

**Comment by isqua** [comment]
Закрываю в пользу вёрстки меню.
